#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AadModernization
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BrutusApp")]
	public partial class BrutusDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BrutusDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BrutusConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BrutusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrutusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrutusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrutusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NYCCallData> NYCCallDatas
		{
			get
			{
				return this.GetTable<NYCCallData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NYCCallData")]
	public partial class NYCCallData
	{
		
		private string _Unique_Key;
		
		private System.Nullable<System.DateTime> _Created_Date;
		
		private System.Nullable<System.DateTime> _Closed_Date;
		
		private string _Agency;
		
		private string _Agency_Name;
		
		private string _Complaint_Type;
		
		private string _Descriptor;
		
		private string _Location_Type;
		
		private string _Incident_Zip;
		
		private string _Incident_Address;
		
		private string _Street_Name;
		
		private string _Cross_Street_1;
		
		private string _Cross_Street_2;
		
		private string _Intersection_Street_1;
		
		private string _Intersection_Street_2;
		
		private string _Address_Type;
		
		private string _City;
		
		private string _Landmark;
		
		private string _Facility_Type;
		
		private string _Status;
		
		private string _Due_Date;
		
		private string _Resolution_Description;
		
		private System.Nullable<System.DateTime> _Resolution_Action_Updated_Date;
		
		private string _Community_Board;
		
		private string _BBL;
		
		private string _Borough;
		
		private System.Nullable<double> _X_Coordinate__State_Plane_;
		
		private System.Nullable<double> _Y_Coordinate__State_Plane_;
		
		private string _Open_Data_Channel_Type;
		
		private string _Park_Facility_Name;
		
		private string _Park_Borough;
		
		private string _Vehicle_Type;
		
		private string _Taxi_Company_Borough;
		
		private string _Taxi_Pick_Up_Location;
		
		private string _Bridge_Highway_Name;
		
		private string _Bridge_Highway_Direction;
		
		private string _Road_Ramp;
		
		private string _Bridge_Highway_Segment;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _Longitude;
		
		private string _Location;
		
		public NYCCallData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unique_Key", DbType="NVarChar(1000)")]
		public string Unique_Key
		{
			get
			{
				return this._Unique_Key;
			}
			set
			{
				if ((this._Unique_Key != value))
				{
					this._Unique_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created_Date
		{
			get
			{
				return this._Created_Date;
			}
			set
			{
				if ((this._Created_Date != value))
				{
					this._Created_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Closed_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Closed_Date
		{
			get
			{
				return this._Closed_Date;
			}
			set
			{
				if ((this._Closed_Date != value))
				{
					this._Closed_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agency", DbType="NVarChar(1000)")]
		public string Agency
		{
			get
			{
				return this._Agency;
			}
			set
			{
				if ((this._Agency != value))
				{
					this._Agency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agency_Name", DbType="NVarChar(1000)")]
		public string Agency_Name
		{
			get
			{
				return this._Agency_Name;
			}
			set
			{
				if ((this._Agency_Name != value))
				{
					this._Agency_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complaint_Type", DbType="NVarChar(1000)")]
		public string Complaint_Type
		{
			get
			{
				return this._Complaint_Type;
			}
			set
			{
				if ((this._Complaint_Type != value))
				{
					this._Complaint_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriptor", DbType="NVarChar(1000)")]
		public string Descriptor
		{
			get
			{
				return this._Descriptor;
			}
			set
			{
				if ((this._Descriptor != value))
				{
					this._Descriptor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Type", DbType="NVarChar(1000)")]
		public string Location_Type
		{
			get
			{
				return this._Location_Type;
			}
			set
			{
				if ((this._Location_Type != value))
				{
					this._Location_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incident_Zip", DbType="NVarChar(1000)")]
		public string Incident_Zip
		{
			get
			{
				return this._Incident_Zip;
			}
			set
			{
				if ((this._Incident_Zip != value))
				{
					this._Incident_Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incident_Address", DbType="NVarChar(1000)")]
		public string Incident_Address
		{
			get
			{
				return this._Incident_Address;
			}
			set
			{
				if ((this._Incident_Address != value))
				{
					this._Incident_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street_Name", DbType="NVarChar(1000)")]
		public string Street_Name
		{
			get
			{
				return this._Street_Name;
			}
			set
			{
				if ((this._Street_Name != value))
				{
					this._Street_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cross_Street_1", DbType="NVarChar(1000)")]
		public string Cross_Street_1
		{
			get
			{
				return this._Cross_Street_1;
			}
			set
			{
				if ((this._Cross_Street_1 != value))
				{
					this._Cross_Street_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cross_Street_2", DbType="NVarChar(1000)")]
		public string Cross_Street_2
		{
			get
			{
				return this._Cross_Street_2;
			}
			set
			{
				if ((this._Cross_Street_2 != value))
				{
					this._Cross_Street_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intersection_Street_1", DbType="NVarChar(1000)")]
		public string Intersection_Street_1
		{
			get
			{
				return this._Intersection_Street_1;
			}
			set
			{
				if ((this._Intersection_Street_1 != value))
				{
					this._Intersection_Street_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intersection_Street_2", DbType="NVarChar(1000)")]
		public string Intersection_Street_2
		{
			get
			{
				return this._Intersection_Street_2;
			}
			set
			{
				if ((this._Intersection_Street_2 != value))
				{
					this._Intersection_Street_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Type", DbType="NVarChar(1000)")]
		public string Address_Type
		{
			get
			{
				return this._Address_Type;
			}
			set
			{
				if ((this._Address_Type != value))
				{
					this._Address_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(1000)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Landmark", DbType="NVarChar(1000)")]
		public string Landmark
		{
			get
			{
				return this._Landmark;
			}
			set
			{
				if ((this._Landmark != value))
				{
					this._Landmark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facility_Type", DbType="NVarChar(1000)")]
		public string Facility_Type
		{
			get
			{
				return this._Facility_Type;
			}
			set
			{
				if ((this._Facility_Type != value))
				{
					this._Facility_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(1000)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Due_Date", DbType="NVarChar(1000)")]
		public string Due_Date
		{
			get
			{
				return this._Due_Date;
			}
			set
			{
				if ((this._Due_Date != value))
				{
					this._Due_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resolution_Description", DbType="NVarChar(1000)")]
		public string Resolution_Description
		{
			get
			{
				return this._Resolution_Description;
			}
			set
			{
				if ((this._Resolution_Description != value))
				{
					this._Resolution_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resolution_Action_Updated_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Resolution_Action_Updated_Date
		{
			get
			{
				return this._Resolution_Action_Updated_Date;
			}
			set
			{
				if ((this._Resolution_Action_Updated_Date != value))
				{
					this._Resolution_Action_Updated_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Community_Board", DbType="NVarChar(1000)")]
		public string Community_Board
		{
			get
			{
				return this._Community_Board;
			}
			set
			{
				if ((this._Community_Board != value))
				{
					this._Community_Board = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBL", DbType="NVarChar(1000)")]
		public string BBL
		{
			get
			{
				return this._BBL;
			}
			set
			{
				if ((this._BBL != value))
				{
					this._BBL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borough", DbType="NVarChar(50)")]
		public string Borough
		{
			get
			{
				return this._Borough;
			}
			set
			{
				if ((this._Borough != value))
				{
					this._Borough = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X_Coordinate__State_Plane_", DbType="Float")]
		public System.Nullable<double> X_Coordinate__State_Plane_
		{
			get
			{
				return this._X_Coordinate__State_Plane_;
			}
			set
			{
				if ((this._X_Coordinate__State_Plane_ != value))
				{
					this._X_Coordinate__State_Plane_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y_Coordinate__State_Plane_", DbType="Float")]
		public System.Nullable<double> Y_Coordinate__State_Plane_
		{
			get
			{
				return this._Y_Coordinate__State_Plane_;
			}
			set
			{
				if ((this._Y_Coordinate__State_Plane_ != value))
				{
					this._Y_Coordinate__State_Plane_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Open_Data_Channel_Type", DbType="NVarChar(1000)")]
		public string Open_Data_Channel_Type
		{
			get
			{
				return this._Open_Data_Channel_Type;
			}
			set
			{
				if ((this._Open_Data_Channel_Type != value))
				{
					this._Open_Data_Channel_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Park_Facility_Name", DbType="NVarChar(1000)")]
		public string Park_Facility_Name
		{
			get
			{
				return this._Park_Facility_Name;
			}
			set
			{
				if ((this._Park_Facility_Name != value))
				{
					this._Park_Facility_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Park_Borough", DbType="NVarChar(1000)")]
		public string Park_Borough
		{
			get
			{
				return this._Park_Borough;
			}
			set
			{
				if ((this._Park_Borough != value))
				{
					this._Park_Borough = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehicle_Type", DbType="NVarChar(1000)")]
		public string Vehicle_Type
		{
			get
			{
				return this._Vehicle_Type;
			}
			set
			{
				if ((this._Vehicle_Type != value))
				{
					this._Vehicle_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taxi_Company_Borough", DbType="NVarChar(1000)")]
		public string Taxi_Company_Borough
		{
			get
			{
				return this._Taxi_Company_Borough;
			}
			set
			{
				if ((this._Taxi_Company_Borough != value))
				{
					this._Taxi_Company_Borough = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taxi_Pick_Up_Location", DbType="NVarChar(1000)")]
		public string Taxi_Pick_Up_Location
		{
			get
			{
				return this._Taxi_Pick_Up_Location;
			}
			set
			{
				if ((this._Taxi_Pick_Up_Location != value))
				{
					this._Taxi_Pick_Up_Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bridge_Highway_Name", DbType="NVarChar(1000)")]
		public string Bridge_Highway_Name
		{
			get
			{
				return this._Bridge_Highway_Name;
			}
			set
			{
				if ((this._Bridge_Highway_Name != value))
				{
					this._Bridge_Highway_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bridge_Highway_Direction", DbType="NVarChar(1000)")]
		public string Bridge_Highway_Direction
		{
			get
			{
				return this._Bridge_Highway_Direction;
			}
			set
			{
				if ((this._Bridge_Highway_Direction != value))
				{
					this._Bridge_Highway_Direction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Road_Ramp", DbType="NVarChar(1000)")]
		public string Road_Ramp
		{
			get
			{
				return this._Road_Ramp;
			}
			set
			{
				if ((this._Road_Ramp != value))
				{
					this._Road_Ramp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bridge_Highway_Segment", DbType="NVarChar(1000)")]
		public string Bridge_Highway_Segment
		{
			get
			{
				return this._Bridge_Highway_Segment;
			}
			set
			{
				if ((this._Bridge_Highway_Segment != value))
				{
					this._Bridge_Highway_Segment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(1000)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
